### ISSUE TITLE
暂无课件的可以写下参考书吗？

### ISSUE THREAD

**Issue by shenxiangzhuang** [ysyisyourbrother/SYSU_Notebook#2]
比如操作系统现在是没有课件的，这些可以写上用的教材和参考书吗？

**Comment by ysyisyourbrother** [comment]
done, click  [here](https://github.com/ysyisyourbrother/SYSU_Notebook/blob/master/%E6%93%8D%E4%BD%9C%E7%B3%BB%E7%BB%9F%20%E5%87%8C%E5%BA%94%E6%A0%87/Readme.md).
Thanks you for reaching out!
